version: '3.9'

services:
  db:
    image: postgres:latest
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_PORT: 5555
    volumes:
      - ./db_data:/docker-entrypoint-initdb.d/
  go:
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./dockerfile
    
 